baseURL: https://givegains.org/
languageCode: en-us
title: GiveGains

# disable taxonomy pages
taxonomies: []

permalinks:
  posts: /:year/:month/:title/

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9
  highlight:
    style: friendly

menu:
  main:
  # individual pages are added to menu in their front matter
  - identifier: contactus
    name: Contact Us
    url: mailto:furies.bogey07@icloud.com
    rel: noopener
    weight: 10
#   - identifier: blog
#     name: Blog
#     url: https://blog.twitter.com/engineering/en_us/topics/open-source
#     rel: noopener
#     weight: 10
#   - identifier: github
#     name: GitHub
#     url: https://github.com/twitter
#     weight: 20
